/**
 * Conversation summarization for long agent contexts.
 *
 * When a chat session grows beyond MAX_INLINE_MESSAGES, the agent server
 * receives only the most recent messages plus a SUMMARY of everything that
 * came before. The summary is generated by the same the3rdacademy OpenAI-
 * compatible endpoint that powers the legacy ai-sdk path, so we get a fast
 * cheap completion without spending Anthropic tokens.
 *
 * The summary is cached in localStorage per session+message-count so we
 * don't re-summarize on every send (only when the older window grows).
 */

import type { ChatMessage } from "@/hooks/useChat";

const SUMMARY_API = "https://the3rdacademy.com/api/chat/completions";
const SUMMARY_MODEL = "kilo-auto/free";
export const RECENT_KEEP = 20;     // always keep the last N raw messages
export const SUMMARIZE_AT = 21;    // start summarizing when total > this
const MAX_SUMMARY_INPUT = 60;      // cap the older window we send to LLM at this many messages
const CACHE_VERSION = "v1";

/**
 * Convert internal ChatMessage objects to the OpenAI message format,
 * collapsing tool calls into compact text so the summarizer sees them too.
 */
function toOpenAIMessages(msgs: ChatMessage[]): Array<{ role: string; content: string }> {
  return msgs.map((m) => {
    let content = m.content || "";
    if (m.toolCalls && m.toolCalls.length > 0) {
      const toolLines = m.toolCalls.map((t) => {
        let argSummary = "";
        try {
          const a = JSON.parse(t.arguments);
          if (a.file_path) argSummary = ` ${a.file_path}`;
          else if (a.command) argSummary = ` $ ${(a.command as string).slice(0, 80)}`;
          else if (a.path) argSummary = ` ${a.path}`;
          else if (a.pattern) argSummary = ` ${a.pattern}`;
        } catch {}
        return `[${t.name}${argSummary}]`;
      });
      content = (content + "\n" + toolLines.join(" ")).trim();
    }
    return {
      role: m.role === "user" ? "user" : "assistant",
      content,
    };
  }).filter((m) => m.content.length > 0);
}

interface CachedSummary {
  // The number of messages this summary covers (= older.length when generated)
  coversCount: number;
  // The summary text itself
  text: string;
  // When generated
  generatedAt: number;
}

function cacheKey(sessionId: string): string {
  return `pipilot:conv-summary:${CACHE_VERSION}:${sessionId}`;
}

function readCache(sessionId: string): CachedSummary | null {
  if (typeof window === "undefined") return null;
  try {
    const raw = localStorage.getItem(cacheKey(sessionId));
    if (!raw) return null;
    const parsed = JSON.parse(raw);
    if (parsed && typeof parsed.text === "string") return parsed;
  } catch {}
  return null;
}

function writeCache(sessionId: string, entry: CachedSummary) {
  if (typeof window === "undefined") return;
  try {
    localStorage.setItem(cacheKey(sessionId), JSON.stringify(entry));
  } catch {}
}

export function clearConversationSummaryCache(sessionId: string) {
  if (typeof window === "undefined") return;
  try { localStorage.removeItem(cacheKey(sessionId)); } catch {}
}

/**
 * Call the3rdacademy completion endpoint with the older messages and ask
 * for a structured summary. Returns the summary text or null on failure.
 */
async function summarizeOlderMessages(older: ChatMessage[]): Promise<string | null> {
  if (older.length === 0) return null;

  // Cap the input to avoid sending huge payloads. Keep the most recent
  // older-window messages — they're the most relevant context for the agent.
  const slice = older.length > MAX_SUMMARY_INPUT
    ? older.slice(older.length - MAX_SUMMARY_INPUT)
    : older;

  const systemPrompt = `You are summarizing a coding-agent conversation so a fresh agent instance can pick up where it left off.

Output a concise structured summary in this exact format:

## Goals
<1-3 lines: what the user is trying to build>

## Done
- <bullet: completed work, list specific files / features>
- <bullet>
- <bullet>

## In Progress
- <bullet: anything started but not finished>

## Decisions
- <bullet: key technical decisions / trade-offs the agent has committed to>

## Open Issues
- <bullet: bugs, blockers, things the user mentioned that aren't resolved>

Rules:
- Be specific. Mention actual file names, function names, design choices.
- Skip filler. No "the user asked", "the assistant said". Just the facts.
- Max 25 lines total.
- Use the past tense for Done, present tense for In Progress.`;

  try {
    const res = await fetch(SUMMARY_API, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model: SUMMARY_MODEL,
        direct_kilo: true,
        stream: false,
        temperature: 0.3,
        messages: [
          { role: "system", content: systemPrompt },
          ...toOpenAIMessages(slice),
          { role: "user", content: "Now write the structured summary as instructed." },
        ],
      }),
    });
    if (!res.ok) {
      console.warn("[summary] non-OK response:", res.status);
      return null;
    }
    const data = await res.json();
    const text =
      data?.choices?.[0]?.message?.content ||
      data?.choices?.[0]?.text ||
      "";
    return typeof text === "string" && text.trim().length > 0 ? text.trim() : null;
  } catch (err) {
    console.warn("[summary] failed:", err);
    return null;
  }
}

/**
 * Top-level helper used by useAgentChat.sendMessage.
 *
 * If the message list is short, returns null and the caller sends as-is.
 * If it's long, generates (or reuses cached) a summary of all messages
 * BEFORE the most-recent RECENT_KEEP, and returns it as a string the caller
 * can prepend to the user prompt.
 */
export async function maybeSummarize(
  sessionId: string,
  messages: ChatMessage[],
): Promise<{ summary: string; olderCount: number; recentCount: number } | null> {
  if (messages.length < SUMMARIZE_AT) return null;

  const older = messages.slice(0, messages.length - RECENT_KEEP);
  const recent = messages.slice(messages.length - RECENT_KEEP);

  // Check cache — if it covers the same older count, reuse
  const cached = readCache(sessionId);
  if (cached && cached.coversCount === older.length) {
    return { summary: cached.text, olderCount: older.length, recentCount: recent.length };
  }

  const summary = await summarizeOlderMessages(older);
  if (!summary) return null;

  writeCache(sessionId, {
    coversCount: older.length,
    text: summary,
    generatedAt: Date.now(),
  });

  return { summary, olderCount: older.length, recentCount: recent.length };
}
